export interface DatePersonale {
  'cuim': string;
  'cnp': string;
  'jud_id': number;
  'status': string;
  'data_juramant': string;
  'cod_parafa': string;
  'nume': string;
  'initiala': string;
  'prenume': string;
  'nume_ant': string;
  'cetatenie': number;
  'act_ident_tip_id': number;
  'act_ident_serie': string;
  'act_ident_nr': string;
  'act_ident_exp_date': string;
  'fac_absolv': number;
  'fac_promotie': number;
  'fac_dipl_serie': string;
  'fac_dipl_nr': string;
  'fac_dipl_data': string;
  'fac_doc_tip': number;
  'fac_rec_emitent': number;
  'fac_rec_serie': string;
  'fac_rec_numar': string;
  'fac_rec_data': string;
  'updated': string;
  'ro': string;
}
